### ISSUE TITLE
blocking bug in vcftocsv

### ISSUE THREAD

**Issue by aurelBZH** [raonyguimaraes/pynnotator#15]
hi, 
thanks for the work on pynnotator. I just install the software, and the installation works well. For the first try i just use` pynnotator test `and i have the following error:

```
 Testing Annotation...
Running Command gunzip -c -d /mnt/data/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/tests/sample.1000.vcf.gz > /mnt/data/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/tests/ann_sample.1000/sample.1000.vcf
2018-06-22 10:41:21.941225 Starting sanity_check:  /mnt/data/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/tests/ann_sample.1000/sample.1000.vcf
sort -k1,1d -k2,2n
2018-06-22 10:41:21.948425 Finished sanity_check, it took:  0:00:00.007200
2018-06-22 10:41:21.948885 Starting snpEff annotation:  sanity_check/sorted.vcf
2018-06-22 10:41:21.948985 Starting decipher annotation:  sanity_check/sorted.vcf
2018-06-22 10:41:21.949938 Starting vep annotation:  sanity_check/sorted.vcf
2018-06-22 10:41:21.950630 Starting snpsift annotation:  sanity_check/sorted.vcf
2018-06-22 10:41:22.116361 Finished decipher annotation, it took:  0:00:00.167376
2018-06-22 10:41:22.197224 Finished snpsift annotation, it took:  0:00:00.246594
Use of uninitialized value in concatenation (.) or string at /home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/vep_data/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/vep_data/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/vep_data/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/vep_data/Plugins/dbNSFP.pm line 227.
Use of uninitialized value in concatenation (.) or string at /home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/vep_data/Plugins/dbNSFP.pm line 227.
2018-06-22 10:41:24.257465 Finished vep annotation, it took:  0:00:02.307527
2018-06-22 10:41:45.991472 Finished snpEff annotation, it took:  0:00:24.042587
2018-06-22 10:41:45.991741 Merging all VCF Files...
2018-06-22 10:41:45.991942 Starting merge:  sanity_check/sorted.vcf

=============================================
vcfanno version 0.2.9 [built with go1.10]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:112: [Flatten] unable to open file: //home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/data/dbsnp/clinvar_20180429.vcf.gz in 
2018-06-22 10:41:46.324350 Finished merge, it took:  0:00:00.332408
2018-06-22 10:41:46.324934 Convert VCF to CSV...
Traceback (most recent call last):
  File "/home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/scripts/vcf2csv.py", line 91, in <module>
    vcf_header = Get_vcfheader(vcffile)
  File "/home/aurelien.beliard/.virtualenvs/pynnotator_env/lib/python3.5/site-packages/pynnotator-1.6-py3.5.egg/pynnotator/scripts/vcf2csv.py", line 89, in Get_vcfheader
    return header_tags
UnboundLocalError: local variable 'header_tags' referenced before assignment
2018-06-22 10:41:46.365109 Finished Annotation, it took 0:00:24.427129

```
Thanks for your help

Aurélien Béliard
bioinformatics engineer
brain and spine institute

**Comment by raonyguimaraes** [comment]
That should have been solved with the latest release.
