### ISSUE TITLE
Refactor concurrency of pynnotator module

### ISSUE THREAD

**Issue by raonyguimaraes** [raonyguimaraes/pynnotator#2]
Exception in thread Thread-7:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/helpers/vcf_annotator.py", line 140, in annotate
    vcf_file = open('%s' % (vcf_file), 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'pynnotator/part.00'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/annotator.py", line 348, in vcf_annotator
    annotator_obj.run()
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/helpers/vcf_annotator.py", line 62, in run
    pool.map(self.annotate, range(1,self.cores+1))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'pynnotator/part.00'

**Comment by raonyguimaraes** [comment]
Exception in thread Thread-7:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/helpers/vcf_annotator.py", line 140, in annotate
    vcf_file = open('%s' % (vcf_file), 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'pynnotator/part.00'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/annotator.py", line 348, in vcf_annotator
    annotator_obj.run()
  File "/projects/mendelmd/mendelmd_source/mendelmdenv/lib/python3.5/site-packages/pynnotator/helpers/vcf_annotator.py", line 62, in run
    pool.map(self.annotate, range(1,self.cores+1))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'pynnotator/part.00'

**Comment by raonyguimaraes** [comment]
This has been sorted.
